"""Build the delivery-delay impact report and reusable visuals."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT_DIR / "dashboard" / "data.js"
OUTPUT_DIR = ROOT_DIR / "docs" / "eda"


def load_data() -> dict:
    text = DATA_FILE.read_text(encoding="utf-8").strip()
    prefix = "window.DVD_DASHBOARD_DATA = "
    if not text.startswith(prefix) or not text.endswith(";"):
        raise ValueError(f"{DATA_FILE} is not valid dashboard data")
    return json.loads(text.removeprefix(prefix).removesuffix(";"))


def save_chart(name: str) -> None:
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / name, dpi=160, bbox_inches="tight")
    plt.close()


def build_report(data: dict) -> str:
    summary = data["summary"]
    delay_bins = pd.DataFrame(data["delayBins"])
    impact = pd.DataFrame(data["delayImpactSummary"]).set_index("segment")
    same_state = pd.DataFrame(data["sameState"]).set_index("segment")

    plt.figure(figsize=(9, 4.8))
    plt.plot(
        delay_bins["range"],
        delay_bins["avg_review"],
        marker="o",
        linewidth=2,
        color="#176b87",
    )
    plt.axhline(4.0, color="#b45309", linestyle="--", linewidth=1.5, label="4.0 stars")
    plt.title("Average review score by delivery delay")
    plt.xlabel("Days versus estimated delivery date")
    plt.ylabel("Average review score")
    plt.xticks(rotation=25, ha="right")
    plt.ylim(0, 5)
    plt.legend()
    save_chart("delivery_delay_review_impact.png")

    plt.figure(figsize=(8, 4.8))
    comparison = impact.loc[["On-time or early", "Late"]]
    axis = comparison["low_review_rate"].plot(kind="bar", color=["#15803d", "#b91c1c"])
    axis.set_title("Low-review rate: late versus on-time or early")
    axis.set_xlabel("")
    axis.set_ylabel("Low-review rate (%)")
    axis.tick_params(axis="x", rotation=0)
    save_chart("late_vs_ontime_low_reviews.png")

    plt.figure(figsize=(8, 4.8))
    same_state.loc[["Same state", "Cross state"], "avg_delivery"].plot(
        kind="bar", color=["#176b87", "#9ca3af"]
    )
    plt.title("Average delivery time by shipment geography")
    plt.xlabel("")
    plt.ylabel("Average delivery days")
    plt.xticks(rotation=0)
    save_chart("same_state_delivery_time.png")

    longest = delay_bins.iloc[-1]
    late = impact.loc["Late"]
    on_time = impact.loc["On-time or early"]
    same = same_state.loc["Same state"]
    cross = same_state.loc["Cross state"]
    lift = late["low_review_rate"] / on_time["low_review_rate"]

    delay_rows = "\n".join(
        f"| `{row['range']}` | {int(row['orders']):,} | {row['avg_review']:.2f} | {row['low_review_rate']:.1f}% |"
        for _, row in delay_bins.iterrows()
    )
    impact_rows = "\n".join(
        f"| `{segment}` | {int(row['orders']):,} | {row['avg_review']:.2f} | {row['low_review_rate']:.1f}% | {row['avg_delay_days']:.2f} |"
        for segment, row in impact.iterrows()
    )

    return f"""# Delivery Delay Impact Analysis

This report is generated by `scripts/build_delivery_delay_analysis.py` from
the deterministic `dashboard/data.js` output produced by the Issue #3
pipeline. It evaluates association between delivery performance and review
outcomes; it does not claim that delay alone proves causation.

## Metric scope

- Analysis unit: one order.
- Delivery-time analysis includes orders with `order_status == delivered` and a non-missing customer-delivery timestamp.
- Delay is customer-delivery date minus estimated-delivery date. Values above zero are late.
- A low review means score `<= 2`. Missing reviews are counted as not low in the late/on-time rate, matching the project metric dictionary.
- Delivered orders with a missing estimated-delivery date have no delay value and remain in the on-time/early denominator, matching the existing `is_late` definition.
- Average review scores ignore missing review scores.
- Same-state results are item-level because shipment geography is joined to order items; they are context, not a separate causal test.

## Delay bins

| Delay bin | Delivered orders | Average review | Low-review rate |
| --- | ---: | ---: | ---: |
{delay_rows}

![Average review score by delivery delay](delivery_delay_review_impact.png)

Average review score falls sharply through the `15-21 days late` group. The
`22+ days late` group rebounds slightly but remains at only
**{longest['avg_review']:.2f} stars**, below the 4.0-star guardrail, with a
low-review rate of **{longest['low_review_rate']:.1f}%**.

## Late versus on-time or early

| Segment | Delivered orders | Average review | Low-review rate | Average delay days |
| --- | ---: | ---: | ---: | ---: |
{impact_rows}

![Low-review rate: late versus on-time or early](late_vs_ontime_low_reviews.png)

Late deliveries have a low-review rate of **{late['low_review_rate']:.1f}%**,
compared with **{on_time['low_review_rate']:.1f}%** for on-time or early
deliveries, or approximately **{lift:.1f}x** higher. The result supports an
association between lateness and dissatisfaction under the documented
denominator rule.

## Same-state context

| Shipment segment | Item rows | Average delivery days | Average review | Late rate |
| --- | ---: | ---: | ---: | ---: |
| Same state | {int(same['items']):,} | {same['avg_delivery']:.2f} | {same['avg_review']:.2f} | {same['late_rate']:.1f}% |
| Cross state | {int(cross['items']):,} | {cross['avg_delivery']:.2f} | {cross['avg_review']:.2f} | {cross['late_rate']:.1f}% |

![Average delivery time by shipment geography](same_state_delivery_time.png)

Same-state shipments average **{same['avg_delivery']:.2f} days**, versus
**{cross['avg_delivery']:.2f} days** cross-state, and have a higher average
review. This difference is consistent with shorter logistics distance, but
other factors such as category, seller, and region may also contribute.

## Business recommendation

Use **22+ days late** as the first delivery-risk guardrail for investigation:
that group falls below 4.0 average stars and has a **{longest['low_review_rate']:.1f}%**
low-review rate. Prioritize intervention before orders reach this threshold,
then monitor whether reducing the 22+ day population improves low-review rate.
Treat the 21-day boundary as an operational trigger, not as proof of a causal
cutoff.

## Reproduction

```bash
python3 scripts/build_delivery_delay_analysis.py
```

The command regenerates this report and the three PNG visuals in `docs/eda/`.
"""


def main() -> None:
    if not DATA_FILE.exists():
        raise FileNotFoundError(f"Dashboard data not found: {DATA_FILE}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "delivery_delay_impact.md").write_text(
        build_report(load_data()), encoding="utf-8"
    )
    print(f"Wrote delivery delay report and three visuals to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
