"""Build the regional demand, delivery, and satisfaction analysis."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT_DIR / "dashboard" / "data.js"
OUTPUT_DIR = ROOT_DIR / "docs" / "eda"


def load_data() -> dict:
    text = DATA_FILE.read_text(encoding="utf-8").strip()
    prefix = "window.DVD_DASHBOARD_DATA = "
    if not text.startswith(prefix) or not text.endswith(";"):
        raise ValueError(f"{DATA_FILE} is not valid dashboard data")
    return json.loads(text.removeprefix(prefix).removesuffix(";"))


def save_chart(name: str) -> None:
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / name, dpi=160, bbox_inches="tight")
    plt.close()


def build_report(data: dict) -> str:
    states = pd.DataFrame(data["regionalDemand"])
    risk_states = pd.DataFrame(data["regionalRisk"])
    same_state = pd.DataFrame(data["sameState"]).set_index("segment")

    top_volume = states.sort_values(["items", "customer_state"], ascending=[False, True]).head(10)
    top_revenue = states.head(10)
    top_three_revenue = states.head(3)["revenue"].sum() / states["revenue"].sum() * 100
    risk_cutoff = 500
    priority = states.merge(
        risk_states[["customer_state", "late_rate", "avg_review"]],
        on="customer_state",
        how="inner",
        suffixes=("_demand", "_risk"),
    )
    priority = priority[
        (priority["items"] >= states["items"].quantile(0.75))
        & (priority["late_rate_risk"] >= risk_states["late_rate"].median())
    ].sort_values(["revenue", "late_rate_risk"], ascending=[False, False])
    risk_display = risk_states.head(10)

    plt.figure(figsize=(9, 5.2))
    volume_chart = top_volume.sort_values("items")
    plt.barh(volume_chart["customer_state"], volume_chart["items"], color="#176b87")
    plt.title("Top customer states by item volume")
    plt.xlabel("Item rows")
    plt.ylabel("Customer state")
    save_chart("regional_demand_by_state.png")

    plt.figure(figsize=(9, 5.2))
    plt.scatter(
        states["items"],
        states["late_rate"],
        s=(states["revenue"] / states["revenue"].max() * 500).clip(lower=30),
        alpha=0.75,
        color="#6b7280",
        edgecolors="white",
        linewidth=0.6,
    )
    for _, row in risk_display.head(5).iterrows():
        plt.annotate(
            row["customer_state"],
            (row["items"], row["late_rate"]),
            xytext=(5, 4),
            textcoords="offset points",
        )
    plt.axvline(
        states["items"].quantile(0.75),
        color="#d97706",
        linestyle="--",
        linewidth=1.2,
        label="75th percentile volume",
    )
    plt.axhline(
        states["late_rate"].median(),
        color="#b91c1c",
        linestyle="--",
        linewidth=1.2,
        label="Median late rate",
    )
    plt.title("Regional demand versus late-delivery risk")
    plt.xlabel("Item rows")
    plt.ylabel("Late rate (%)")
    plt.legend()
    save_chart("regional_demand_vs_risk.png")

    volume_rows = "\n".join(
        f"| {row['customer_state']} | {int(row['items']):,} | {row['revenue']:,.2f} | {row['avg_review']:.2f} | {row['late_rate']:.1f}% |"
        for _, row in top_volume.iterrows()
    )
    revenue_rows = "\n".join(
        f"| {row['customer_state']} | {int(row['items']):,} | {row['revenue']:,.2f} | {row['avg_review']:.2f} | {row['late_rate']:.1f}% |"
        for _, row in top_revenue.head(10).iterrows()
    )
    risk_rows = "\n".join(
        f"| {row['customer_state']} | {int(row['items']):,} | {row['revenue']:,.2f} | {row['avg_delivery']:.2f} | {row['late_rate']:.1f}% | {row['low_review_rate']:.1f}% |"
        for _, row in risk_display.iterrows()
    )
    priority_rows = "\n".join(
        f"| {row['customer_state']} | {int(row['items']):,} | {row['revenue']:,.2f} | {row['late_rate_risk']:.1f}% | {row['avg_review_risk']:.2f} |"
        for _, row in priority.head(8).iterrows()
    )

    return f"""# Regional Demand, Delivery, and Satisfaction Analysis

This report is generated by scripts/build_regional_analysis.py from the
deterministic dashboard/data.js output produced by the shared pipeline.
Regional metrics use customer state and item-level joins, as defined in the
project metric dictionary.

## Method and guardrails

- Demand is measured by item rows and item-price revenue by customer state.
- Delivery and satisfaction metrics in the risk view use delivered item rows; demand volume and revenue use all item rows.
- States with fewer than **{risk_cutoff} item rows** are excluded from the risk ranking to reduce small-sample volatility.
- The risk chart shows all states, but its highlighted risk table uses the minimum-volume rule.
- State comparisons are descriptive and do not prove that geography alone causes delay or low reviews.

## Demand concentration

![Top customer states by item volume](regional_demand_by_state.png)

The top three states by revenue account for **{top_three_revenue:.1f}%** of total
state-level item revenue. This concentration makes improvements in major
markets more consequential, but volume alone is not a reason to invest without
checking delivery and satisfaction.

### Top states by item volume

| State | Item rows | Revenue | Average review | Late rate |
| --- | ---: | ---: | ---: | ---: |
{volume_rows}

### Top states by revenue

| State | Item rows | Revenue | Average review | Late rate |
| --- | ---: | ---: | ---: | ---: |
{revenue_rows}

## Delivery-risk view

![Regional demand versus late-delivery risk](regional_demand_vs_risk.png)

The risk ranking uses at least {risk_cutoff} item rows per state and is ordered
by late rate, then average delivery time. The largest late-rate values should
be interpreted alongside volume and review metrics rather than treated as
standalone priorities.

| State | Item rows | Revenue | Average delivery days | Late rate | Low-review rate |
| --- | ---: | ---: | ---: | ---: | ---: |
{risk_rows}

## Priority regions

The following view combines high demand (at or above the 75th percentile of
state item volume) with at-or-above-median late rate. It is a prioritization
screen, not a causal model.

| State | Item rows | Revenue | Late rate | Average review |
| --- | ---: | ---: | ---: | ---: |
{priority_rows}

## Seller-state and customer-state context

Same-state shipments average **{same_state.loc['Same state', 'avg_delivery']:.2f}**
delivery days versus **{same_state.loc['Cross state', 'avg_delivery']:.2f}**
cross-state, with late rates of **{same_state.loc['Same state', 'late_rate']:.1f}%**
and **{same_state.loc['Cross state', 'late_rate']:.1f}%**, respectively. This
supports treating logistics distance as a useful supporting factor; seller
quality, category mix, and destination mix still need to be considered.

## Recommendation

Prioritize operational review in the intersection of high demand and elevated
late rate, starting with the priority table above. For lower-volume states,
continue monitoring until at least {risk_cutoff} item rows are available before
making a firm regional investment decision. Pair regional actions with monthly
late-rate, delivery-time, and low-review monitoring.

## Reproduction

    python3 scripts/build_regional_analysis.py

The command regenerates this report and the two PNG visuals in docs/eda/.
"""


def main() -> None:
    if not DATA_FILE.exists():
        raise FileNotFoundError(f"Dashboard data not found: {DATA_FILE}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "regional_analysis.md").write_text(
        build_report(load_data()), encoding="utf-8"
    )
    print(f"Wrote regional analysis report and two visuals to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
