"""Build the baseline order-journey EDA report and reusable visuals."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT_DIR / "dashboard" / "data.js"
OUTPUT_DIR = ROOT_DIR / "docs" / "eda"


def load_dashboard_data() -> dict:
    text = DATA_FILE.read_text(encoding="utf-8").strip()
    prefix = "window.DVD_DASHBOARD_DATA = "
    if not text.startswith(prefix) or not text.endswith(";"):
        raise ValueError(f"{DATA_FILE} is not valid dashboard data")
    return json.loads(text.removeprefix(prefix).removesuffix(";"))


def save_chart(name: str) -> None:
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / name, dpi=160, bbox_inches="tight")
    plt.close()


def build_report(data: dict) -> str:
    summary = data["summary"]
    metadata = data["metadata"]
    status = pd.DataFrame(data["statusCounts"]).set_index("status")["orders"]
    review_frame = pd.DataFrame(data["reviewDistribution"])
    review_counts = review_frame.set_index("score")["count"]
    monthly_frame = pd.DataFrame(data["monthlyOrders"])
    monthly = monthly_frame.set_index("month")["orders"]
    weekdays = pd.DataFrame(data["weekdayOrders"]).set_index("weekday")["orders"]

    delivered = int(status["delivered"])
    reviewed = int(review_frame["count"].sum())
    high_reviews = int(review_frame.loc[review_frame["score"] >= 4, "count"].sum())
    low_reviews = int(review_frame.loc[review_frame["score"] <= 2, "count"].sum())
    peak_month = monthly.idxmax()
    peak_month_count = int(monthly.max())
    peak_weekday = weekdays.idxmax()
    peak_weekday_count = int(weekdays.max())
    delivery_share = delivered / summary["orders"] * 100
    high_review_share = high_reviews / reviewed * 100
    low_review_share = low_reviews / reviewed * 100

    plt.figure(figsize=(10, 4.8))
    plt.plot(monthly.index, monthly.values, marker="o", color="#176b87", linewidth=2)
    plt.title("Monthly order volume")
    plt.xlabel("Purchase month")
    plt.ylabel("Orders")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", alpha=0.25)
    save_chart("monthly_orders.png")

    plt.figure(figsize=(8, 4.8))
    plt.bar(weekdays.index, weekdays.values, color="#d97706")
    plt.title("Orders by purchase weekday")
    plt.xlabel("Weekday")
    plt.ylabel("Orders")
    plt.xticks(rotation=25, ha="right")
    save_chart("weekday_orders.png")

    plt.figure(figsize=(8, 4.8))
    status.sort_values().plot(kind="barh", color="#315c8a")
    plt.title("Order status distribution")
    plt.xlabel("Orders")
    plt.ylabel("Status")
    save_chart("order_status.png")

    plt.figure(figsize=(7, 4.8))
    plt.bar(review_counts.index.astype(str), review_counts.values, color="#b45309")
    plt.title("Review-score distribution")
    plt.xlabel("Review score")
    plt.ylabel("Review rows")
    save_chart("review_distribution.png")

    outcome = pd.Series({"Delivered status": delivered, "Other statuses": summary["orders"] - delivered})
    plt.figure(figsize=(7, 4.8))
    plt.bar(outcome.index, outcome.values, color=["#15803d", "#9ca3af"])
    plt.title("Order status: delivered vs other")
    plt.ylabel("Orders")
    save_chart("delivery_outcomes.png")

    status_rows = "\n".join(f"| `{label}` | {count:,} |" for label, count in status.items())
    return f"""# Baseline Order-Journey EDA

This report is generated by `scripts/build_order_journey_eda.py` from the
deterministic `dashboard/data.js` output. That output is built from
`Dataviz_proj_all_datasets.xlsx` by the Issue #3 pipeline. The analysis is
order-level unless stated otherwise. It is intended to establish the
marketplace baseline before the regional, product, seller, and delivery-impact
analyses.

## Scope and data handling

- Source: `orders_dataset` and `order_reviews_dataset` through the validated dashboard pipeline.
- One row in the order table represents one order; the upstream pipeline preserves the source row grain.
- Review distribution uses review rows directly, so an order can contribute more than one review row if present.
- A completed delivery means `order_status == delivered` and a non-missing `order_delivered_customer_date`, matching the project metric dictionary.
- No orders are removed for this baseline overview. Missing timestamps and missing reviews follow the project metric dictionary denominator rules.

## Scale snapshot

| Measure | Value |
| --- | ---: |
| Orders | {summary["orders"]:,} |
| Items | {metadata["rowCounts"]["items"]:,} |
| Sellers | {summary["sellers"]:,} distinct sellers |
| Customers | {summary["customers"]:,} distinct customer identities |
| Products | {summary["products"]:,} distinct products |
| Review rows | {reviewed:,} |
| Average review score | {summary["avgReview"]:.2f} |
| High reviews (4-5) | {high_review_share:.1f}% |
| Low reviews (1-2) | {low_review_share:.1f}% |
| Orders with delivered status | {delivered:,} ({delivery_share:.1f}% of orders) |

## Order status

| Status | Orders |
| --- | ---: |
{status_rows}

The marketplace is overwhelmingly delivered orders, but the non-delivered
statuses remain important for understanding the gap between placed orders and
successful customer completion.

![Order status distribution](order_status.png)

## Timing patterns

![Monthly order volume](monthly_orders.png)

Order volume peaks in **{peak_month}** with **{peak_month_count:,} orders**.
The weekday pattern peaks on **{peak_weekday}** with **{peak_weekday_count:,} orders**.
These patterns provide the baseline for checking whether later segments differ
from the overall marketplace seasonality or weekly rhythm.

![Orders by purchase weekday](weekday_orders.png)

## Customer satisfaction

![Review-score distribution](review_distribution.png)

Five-star reviews are the largest group, while the low-review share is still
large enough to warrant operational investigation. The review distribution is
descriptive only here; delivery speed and category differences should be
tested in the dedicated downstream analyses.

## Delivery status coverage

![Completed delivery records](delivery_outcomes.png)

This overview chart uses the exact order-status split. Delivery-time metrics
use the stricter project definition requiring both `delivered` status and a
non-missing customer-delivery timestamp; those metrics are validated by the
project pipeline separately.

## Hypotheses for deeper analysis

1. Longer delivery times are associated with lower review scores and a higher
   low-review rate; test this with delivery-day bins and late-versus-on-time
   comparisons.
2. The marketplace's overall satisfaction hides category and regional risk;
   test whether high-volume categories or states combine meaningful demand
   with worse delivery or review outcomes.
3. The weekday and monthly demand pattern may change the operational load on
   sellers; test whether peak periods have higher delays after controlling for
   category and region.

## Reproduction

```bash
python3 scripts/build_order_journey_eda.py
```

The command regenerates this report and the five PNG visuals in `docs/eda/`.
"""


def main() -> None:
    if not DATA_FILE.exists():
        raise FileNotFoundError(f"Dashboard data not found: {DATA_FILE}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    data = load_dashboard_data()
    (OUTPUT_DIR / "order_journey_eda.md").write_text(build_report(data), encoding="utf-8")
    print(f"Wrote report and five visuals to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
